package main

import (
	"finance-tracking-app/config"
	"finance-tracking-app/database"
	"finance-tracking-app/handlers"
	"finance-tracking-app/repositories"
	"finance-tracking-app/services"
	"fmt"
	"log"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "finance-tracking-app/docs" // This will be generated by swag init
)

// @title Finance Tracking API
// @version 1.0
// @description A comprehensive personal finance tracking application API with budget management, expense tracking, and analytics
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url https://github.com/yourusername/finance-tracking-app
// @contact.email support@financeapp.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8081
// @BasePath /api/v1
// @schemes http https

func main() {
	// Load configuration
	config.LoadConfig()

	// Initialize database
	database.InitDB()

	// Get database instance
	db := database.GetDB()

	// Initialize repositories
	incomeRepo := repositories.NewIncomeRepository(db)
	categoryRepo := repositories.NewExpenseCategoryRepository(db)
	budgetRepo := repositories.NewCategoryBudgetRepository(db)
	expenseRepo := repositories.NewExpenseRepository(db)
	allocationRepo := repositories.NewBudgetAllocationRepository(db)
	reallocationRepo := repositories.NewBudgetReallocationRepository(db)
	alertRepo := repositories.NewBudgetAlertRepository(db)

	// Initialize services
	incomeService := services.NewIncomeService(incomeRepo, categoryRepo, budgetRepo, allocationRepo, db)
	categoryService := services.NewCategoryService(categoryRepo)
	expenseService := services.NewExpenseService(expenseRepo, categoryRepo, budgetRepo, db)
	budgetService := services.NewBudgetService(budgetRepo, incomeRepo, allocationRepo, reallocationRepo, categoryRepo, db)
	transactionService := services.NewTransactionService(incomeRepo, expenseRepo)
	analyticsService := services.NewAnalyticsService(expenseRepo, budgetRepo, categoryRepo)
	reportService := services.NewReportService(incomeRepo, expenseRepo, budgetRepo, categoryRepo, allocationRepo)
	alertService := services.NewAlertService(alertRepo, budgetRepo, categoryRepo)
	schedulerService := services.NewSchedulerService(reportService)

	// Initialize handlers
	incomeHandler := handlers.NewIncomeHandler(incomeService)
	categoryHandler := handlers.NewCategoryHandler(categoryService)
	expenseHandler := handlers.NewExpenseHandler(expenseService)
	budgetHandler := handlers.NewBudgetHandler(budgetService)
	transactionHandler := handlers.NewTransactionHandler(transactionService)
	analyticsHandler := handlers.NewAnalyticsHandler(analyticsService)
	reportHandler := handlers.NewReportHandler(reportService)
	alertHandler := handlers.NewAlertHandler(alertService)

	// Setup Gin router
	router := gin.Default()

	// CORS configuration
	router.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Length", "Content-Type", "Authorization", "Accept", "X-Requested-With", "X-CSRF-Token", "Accept-Encoding", "Cache-Control"},
		ExposeHeaders:    []string{"Content-Length", "Content-Type"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
	}))

	// Health check
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "ok",
			"service": "finance-tracking-api",
		})
	})

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		// Income routes
		incomes := v1.Group("/incomes")
		{
			incomes.POST("", incomeHandler.CreateIncome)
			incomes.GET("", incomeHandler.GetIncomes)
			incomes.GET("/:id", incomeHandler.GetIncomeByID)
			incomes.PATCH("/:id", incomeHandler.UpdateIncome)
			incomes.DELETE("/:id", incomeHandler.DeleteIncome)
		}

		// Category routes
		categories := v1.Group("/categories")
		{
			categories.POST("", categoryHandler.CreateCategory)
			categories.GET("", categoryHandler.GetCategories)
			categories.GET("/:id", categoryHandler.GetCategoryByID)
			categories.PATCH("/:id", categoryHandler.UpdateCategory)
			categories.DELETE("/:id", categoryHandler.DeleteCategory)
		}

		// Expense routes
		expenses := v1.Group("/expenses")
		{
			expenses.POST("", expenseHandler.CreateExpense)
			expenses.GET("", expenseHandler.GetExpenses)
			expenses.GET("/:id", expenseHandler.GetExpenseByID)
			expenses.PATCH("/:id", expenseHandler.UpdateExpense)
			expenses.DELETE("/:id", expenseHandler.DeleteExpense)
		}

		// Budget routes
		budgets := v1.Group("/budgets")
		{
			budgets.GET("", budgetHandler.GetBudgets)
			budgets.GET("/summary", budgetHandler.GetBudgetSummary)
			budgets.POST("/reallocate", budgetHandler.ReallocateBudget)
			budgets.GET("/reallocations", budgetHandler.GetReallocations)
			budgets.DELETE("/reallocate/:id", budgetHandler.CancelReallocation)
		}

		// Transaction routes
		transactions := v1.Group("/transactions")
		{
			transactions.GET("", transactionHandler.GetTransactions)
		}

		// Analytics routes
		analytics := v1.Group("/analytics")
		{
			analytics.GET("/spending-pattern", analyticsHandler.GetSpendingPattern)
			analytics.GET("/category-comparison", analyticsHandler.GetCategoryComparison)
			analytics.GET("/top-spending", analyticsHandler.GetTopSpending)
			analytics.GET("/budget-performance", analyticsHandler.GetBudgetPerformance)
		}

		// Report routes
		reports := v1.Group("/reports")
		{
			reports.GET("/monthly", reportHandler.GetMonthlyReport)
			reports.GET("/monthly/export", reportHandler.ExportMonthlyReport)
			reports.GET("/yearly", reportHandler.GetYearlyReport)
			reports.GET("/yearly/export", reportHandler.ExportYearlyReport)
		}

		// Alert routes
		alerts := v1.Group("/alerts")
		{
			alerts.GET("", alertHandler.GetAlerts)
			alerts.POST("", alertHandler.CreateAlert)
			alerts.PATCH("/:id", alertHandler.UpdateAlert)
			alerts.DELETE("/:id", alertHandler.DeleteAlert)
		}
	}

	// Start scheduler service for automated tasks
	schedulerService.Start()
	defer schedulerService.Stop()

	// Start server
	port := config.AppConfig.ServerPort
	addr := fmt.Sprintf(":%s", port)
	fmt.Printf("🚀 Server running on http://localhost%s\n", addr)
	fmt.Printf("📚 Swagger Documentation: http://localhost%s/swagger/index.html\n", addr)
	fmt.Printf("💚 Health Check: http://localhost%s/health\n", addr)
	fmt.Printf("⏰ Scheduler: Monthly report auto-generation enabled\n")

	if err := router.Run(addr); err != nil {
		log.Fatal("Failed to start server:", err)
	}
}
